### ISSUE TITLE
看不懂啊

### ISSUE THREAD

**Issue by LHMZ112** [linjiananallnt/ElectricRat#11]
![image](https://github.com/linjiananallnt/ElectricRat/assets/142554087/d4fafdf3-fc86-4529-a2ab-b56c6ff5b01d)

**Comment by linjiananallnt** [comment]
如果存在第一次的安装错误，请将容器全部删除后，再次运行`sudo docker-compose up -d`。
在复杂的docker环境下，可以通过DinD技术来解决。
