### ISSUE TITLE
docker 搭建返回404

### ISSUE THREAD

**Issue by xiaolushuo** [linjiananallnt/ElectricRat#2]
<img width="496" alt="Snipaste_2023-03-01_11-20-08" src="https://user-images.githubusercontent.com/16830990/222036622-7b6b385a-6365-4b87-83db-5f3d15ecf909.png">

**Comment by linjiananallnt** [comment]
等待一下，多刷新几次。docker 安装 tomcat 释放 war 文件需要时间。
如果问题还得不到解决，可以通过 `sudo docker ps -a` 查看容器状态。
并且通过 `sudo docker logs electricrat-ewb` 查看日志进行排错。
最后检查 `http://127.0.0.1:12666/ElectricRat/index.html` 路径拼写是否正确。
> 注意：在 v1.1.0 版本后容器名更名为 electricrat-web，如果您是使用 v1.1.0 版本 进行搭建那么查看日志的命令为：`sudo docker logs electricrat-web`

**Comment by linjiananallnt** [comment]
目前就该问题已做解答，如果后续还存在问题欢迎积极提交 Issues~
